Repository libsndfile/libsndfile, pull requests merged in 2020-11, with the labels that each got.

#650 SF_BROADCAST_INFO -> SF_LOOP_INFO
  docs/command.md
Labels: documentation

#651 Fix memory leak in aiff_read_header
  src/aiff.c
Labels: Bug

#655 Fixed typo in FindSQLite3.cmake file
  cmake/sqlite/FindSQLite3.cmake
Labels: Bug, cmake

#657 Fix use of uninitialized value in exif_subchunk_parse
  src/wavlike.c
Labels: Bug
