Repository libsndfile/libsndfile, pull requests merged in 2021-01, with the labels that each got.

#689 Fix use of uninitialized value in endswap_int64_t_array
  src/double64.c
Labels: Bug

#690 fix api.md table error
  docs/api.md
Labels: documentation

#677 Improving header documentation.
  include/sndfile.h.in
Labels: question
